name : 20-03-24-SimpleEvent
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hellow world"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye world"
  