name : 21-03-24-Artifacts
on: workflow_dispatch
jobs:
 app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: build
        run: mvn install   
      - name: artifact-upload
        uses: actions/uploadartifact-@v4   
        with:
          name : todo-artifact
          path: /target

      
