name: 20-03-24-Task
on: 
    workflow_dispatch:
        inputs:
            javaversion:
                type: string
                #default :amarjit

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{inputs.javaversion}}
          cache: 'maven'
         

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true
  
      - name: version creation
        id: version
        run: |
          echo $JAVA_VER
          echo "javaversion=${{inputs.javaversion}}" > $JAVA_VER

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
        - name: Display java version information
          run: echo "JAVA Version:" ${{steps.version.JAVA_VER}}

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download web-app content
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: target/
           
  