name : 20-03-24-context_variable
on: workflow_dispatch
env:
    localenvvar:${{var.test.TESTDBCS}}     
jobs:
    my-first-job:
      runs-on: ubuntu-latest
      steps:
        - name: test
         
          run: |
            echo "Environment Variable :${{github.event_name}}"
            echo "Local variable : ${{env.localenvvar}}"
