name : 21-03-24-EventFilter
on:
    push:
      branches:
        - 'main'
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "manual workflow"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Manual workflowgit"
  