name : 20-03-24-context
on: workflow_dispatch
jobs:
    my-first-job:
      runs-on: ubuntu-latest
      steps:
        - name: test
          run: |
            echo "Github Event name :${{github.event_name}}"
            echo "ref :${{github}}"
            echo "Sha : ${{github.sha}}"
