name : 20-03-24-context_variable
on: workflow_dispatch
env:
    localenvvar: ${{vars.TESTDBCS}}     
jobs:
    build:
      runs-on: ubuntu-latest
      environment: test
      steps:
        - name: test
         
          run: |
            echo "Environment Variable :${{github.event_name}}"
            echo "Local variable : ${{env.localenvvar}}"
