name : 22-03-24-shellscript
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
         chmod +x ../../init.sh
         ./init.sh

  my-second-job:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Bye world"
      
